Build jwt authentication
gymbarr/crown-clothing-api pull request #1
Opened 2022-12-18 14:00 UTC by gymbarr

2022-12-19 09:50 UTC, kladaFOX requested changes

2022-12-19 09:50 UTC, kladaFOX commented on app/controllers/authentication_controller.rb
> +  before_action :authorize_request, except: :login
Странно, если у тебя тут 1 экшен

2022-12-19 09:50 UTC, kladaFOX commented on app/controllers/users_controller.rb
> +  end
Что будет если твой апдейт повалится? Что ты вернешь на фронт?

2022-12-19 09:50 UTC, kladaFOX commented on app/controllers/users_controller.rb
> +  end
Этот рескью надо вынести в application_controller

2022-12-19 09:50 UTC, kladaFOX commented on app/models/user.rb
> +  validates :username, presence: true, uniqueness: true, format: { with: VALID_USERNAME_REGEX }
Никогда не юзай валидацию на уникальность без соответствующего индекса в БД. МОжно произойти ситуация когда у тебя придет 2 паралельных запроса и они пройдут валидацию на уровне рельсы, т.к. в БД еще нет ни 1 записи и у тебя в БД будет 2 неуникальных записи. Поэтому даже rubocop ругается на использование этой валидации без индекса. `add_index :users, :emal, uniqueness: true` помоему так

2022-12-19 09:50 UTC, kladaFOX commented on db/migrate/20221216073742_create_users.rb
> +  end
Вот сюда индексы нужно добавить

2022-12-19 09:50 UTC, kladaFOX commented on config/routes.rb
> +  get '/*a', to: 'application#not_found'
Не понял для чего этот роут? По идее ты должен перехватывать ошибку Record NotFound в application_controller и там рендерить какой то json

2022-12-19 09:50 UTC, kladaFOX commented on config/routes.rb
> +  resources :users, param: :_username
а зачем нижнее подчеркивание у параметра _username?

2022-12-19 09:50 UTC, kladaFOX commented on spec/requests/users/delete_user_spec.rb
> +        expect(User.all.count).to eq(0)
.count можно юзать прямо на модели .all не нужен

2022-12-19 09:50 UTC, kladaFOX commented on spec/requests/users/delete_user_spec.rb
> +      let(:headers) { { 'Authorization' => user_token(user) } }
Так вынеси этот хеш в свой хелпер чтобы он тебе сразу возвращал то что нужно. 
`let(:headers) { user_auth_header(user) }`

2022-12-19 09:52 UTC, kladaFOX commented
А и еще добавь тесты на свои сервисы

2022-12-19 10:01 UTC, gymbarr commented on app/controllers/authentication_controller.rb
> +  before_action :authorize_request, except: :login
лучше использовать skip_before_action?

2022-12-19 10:03 UTC, gymbarr commented on app/controllers/users_controller.rb
> +  end
так то, что в условии, и верну
а вот правильно ли то, что в случае успешного обновления я ничего не возвращаю?

2022-12-19 10:07 UTC, gymbarr commented on app/controllers/users_controller.rb
> +  end
и я так понимаю, что этот эксепшн можно использовать не только для юзера, но и для любой записи ActiveRecord и рендерить ошибку: 'Record not found'?

2022-12-19 10:09 UTC, gymbarr commented on app/models/user.rb
> +  validates :username, presence: true, uniqueness: true, format: { with: VALID_USERNAME_REGEX }
я собирался это сделать чуть позже. просто ПР и так немаленький вышел)

2022-12-19 10:10 UTC, kladaFOX commented on app/controllers/authentication_controller.rb
> +  before_action :authorize_request, except: :login
а  я не так понял. Да если ты хочешь скипать лучше skip это намного нагляднее

2022-12-19 10:13 UTC, kladaFOX commented on app/controllers/users_controller.rb
> +  end
Упс сорян, имел в виду наоборот если у тебя апдейт удачно пройдет ты вернешь 204 No content а лучше наверное что то иное типо success true хз

2022-12-19 10:13 UTC, kladaFOX commented on app/controllers/users_controller.rb
> +  end
Да, конечно

2022-12-19 10:14 UTC, kladaFOX commented on app/models/user.rb
> +  validates :username, presence: true, uniqueness: true, format: { with: VALID_USERNAME_REGEX }
Не так ты если добавляешь проверку на уникально то сразу идет индекс, потому что потом забудешь))

2022-12-19 10:20 UTC, gymbarr commented on app/models/user.rb
> +  validates :username, presence: true, uniqueness: true, format: { with: VALID_USERNAME_REGEX }
рубокоп напомнит) но вообще по делу, согласен

2022-12-19 10:22 UTC, gymbarr commented on config/routes.rb
> +  resources :users, param: :_username
роуты я скопировал из статьи, решил оставить как есть
но тут _ походу лишнее, исправлю

2022-12-19 10:25 UTC, gymbarr commented on config/routes.rb
> +  get '/*a', to: 'application#not_found'
это вроде бы защита от того, что если пришел вообще какой-то левый запрос на api
и тогда будет рендериться ответ: 'Not found'

2022-12-19 10:32 UTC, kladaFOX commented on config/routes.rb
> +  get '/*a', to: 'application#not_found'
А ну это по дефолту резолвиться статическими страницами public/404.html

2022-12-19 11:29 UTC, gymbarr commented on config/routes.rb
> +  get '/*a', to: 'application#not_found'
ну да, сейчас в postman протестил, все гуд работает

2022-12-19 11:33 UTC, gymbarr commented on app/controllers/application_controller.rb
> +      render json: { errors: e.message }, status: :unauthorized
Этот эксепшн тоже можно убирать, получается?

2022-12-19 12:01 UTC, gymbarr commented on app/controllers/concerns/authorization.rb
> +        render json: { errors: e.message }, status: :unauthorized
Этот эксепшн можно убрать, получается?
Если у меня уже есть общий

2022-12-19 17:05 UTC, gymbarr commented on config/routes.rb
> +  resources :users, param: :_username
_ позволяет избежать дублирования параметра :username в объекте params при обновлении поля username пользователя

2022-12-20 09:43 UTC, kladaFOX requested changes

2022-12-20 09:43 UTC, kladaFOX commented on app/controllers/concerns/authorization.rb
> +        render json: { errors: e.message }, status: :unauthorized
нее тут статус unauth.

2022-12-20 09:43 UTC, kladaFOX commented on db/migrate/20221219120003_add_index_to_users_email.rb
> +  end
Ну ток это надо было пихать в 1 миграцию с явным названием AddUniqueIndexesToUsers

2022-12-20 09:50 UTC, gymbarr commented on db/migrate/20221219120003_add_index_to_users_email.rb
> +  end
окей, учту

2022-12-20 13:32 UTC, merged